### PR TITLE
Can now edit the the and add to the regex

### PR DESCRIPTION
**Pull request by itf**
Also works on i3 window manager.

### CODE REVIEW

**Comment by frans-fuerst** [comment]
Hi Ivan, thanks for the patch!
Quite a bit of work you contributed.. I'm just having a look right now and then I will merge it into master.
I will apply some changes regarding the (planned) possibility to start track as a background process which the UI can connect to. 
I was planning to start a track server (that is the `track_server` script you deleted) which collects all data and connect via pyzmq. Do you have any experience with ZMQ?

**Comment by itf** [comment]
Hi frans!

I'm gonna delete the pull request an
And make a more organized one later.
There are some extra bug fixes I've added, but I was too busy to edit the
pull request tonight, I was too sleep and ended up making a not very good
pull request.

I haven't heard about pzmq, is it a website server in the same way as
nginx? I could try to help with the project,  since it is a tool I'd likely
use in a daily basis.

Some extra info:
We are using track on a hackathon to make a time tracker for
classes/college. I'm gonna send you the link to the final result! It's
being integrated with a fb parse service and an android app (which wouldn't
go to the patch).  The extra work is being done in the branch "mit" if you
are curious

**Comment by frans-fuerst** [comment]
ZMQ is a inproc/ipc/tcp based communication and message queue abstraction library which can be used to let two processes communicate in a very easy way and with bindings for virtually every programming language of interest (see http://zguide.zeromq.org/page:all).
Of course one option would be to implement a http based server in the first place but I'd prefer to leave the http/html stuff optional and turn this into an extra component/project.
Maybe I'll try to make some progress on the master branch to be able to demonstrate what I'm talking about. 
Anyway - the goal should be to separate the core application from the UI in order to be able to run it on startup and to be able send requests (e.g. on command line). This would also improve testability.

**Comment by frans-fuerst** [comment]
Regarding the hackathon - that sounds interesting of course. Can you provide some details (is it taking place right now?, topic, etc.)? And maybe some details about the requirements on track (e.g. will Windows be involved?)

**Comment by itf** [comment]
It is taking place right now, it is called "HackMIT", it is a software and
hardware hackathon, mostly focused in proprietary apis (since the companies
that sponsor the hackathon want people to use their api), but you can do
whatever you want.
 Our team is not really trying to win, but rather make a tool that we are
gonna use.

At the moment we were only intending to support the mainstream
distributions of linux

---

_Ivan Tadeu Ferreira Antunes Filho_

2015-09-20 7:53 GMT-04:00 Frans Fürst notifications@github.com:

**Pull request closed without merging**
