### PR TITLE
Regex rules

### PR DESCRIPTION
**Pull request by itf**
Makes it possible to create new regex rules on the go.
When modifying a rule, it is saved to a text file
Updates the category of all previous windows based on the new rules.
Hard codes 0 to be private and anything else to be working

Adds an exception catch when trying to get the process name, to make it possible to run the program in i3 (empirically tested)

Now, it is a proper pull request

### CODE REVIEW

**Comment by frans-fuerst** [comment]
Thanks! I've merged your changes in. There are some minor modifications I'm going to apply regarding the separation of a Qt-free server and the Qt based UI. I'd like to have a track_server which imports stuff from `track_base/` and the track-ui importing from `track_qt`

**Comment by frans-fuerst** [comment]
In case you're still interested in the development: `track-cli` will provide a way to communicate with the `track_server` on the command line. The next steps will be to carefully move the tracking stuff into `track_server` and `track_base` (testing with `track-cli`) and then making the UI and it's models get the data from the server via `zmq`.

**Comment by itf** [comment]
I'm interested in the development, but I will probably just add things to the UI. There are 4 things that I'd like to add:
I want to be able to get the time spent in different categories, 
to be able to show the different categories with different colors on the graph,
to be able to drag the rules and change their order,
to be able to add a project-hamster like feature, i.e. write the name of what you are working or was supposed to be working on, and while this is running, it appends this name to the end of the active window title when logging, or, in case you are idle, to save the data in such way that also save the name of what you were in theory working on.

**Comment by frans-fuerst** [comment]
Sounds good. Some of your suggestions are already listed in `progress.md` and some (like the categories are partly implemented in the 'total/active/work/idle' field. I'd suggst a couple of things:
- to avoid conflicts I will first complete the server/UI separation. 
- `progress.md` should be turned into tickets
- maybe we should communicate UI modifications/concepts using an svg based mockup

What's your opinion?

**Comment by itf** [comment]
ok!

I don't know if I will really have time to implement those things, this semester.
 If I have time, I have never done anything related to the UI before, so I don't think I'd be able to show how it would look like using the svg mockup. I can tell/discuss the concepts of what I'm trying to change with no problems, though

**Pull request merged**
